---
title: "Progress report - Age-structured open population distance sampling model"
output: html_notebook
---

## To-Do

##### 04/12-2019

At the current state, I do have a functioning model that is ready for modification. Because time limits are short, this is how I will work to solve the last remining issues; 

- Derived parameters; 
  - OK - done!
- Prepare real data from Lierne
  - Extract data from "Hønsefuglportalen", because we need data from 2019 as well
      - OK - done. Model runs!
- Update R-function
  - OK - done!
- Make model for survival
  - First - use informative prior based on radio-telemetry study. Common survival and year-specific survival 
      - Ok - done!

##### 05/12-2019
- Add model for breeding succes based on data from monitored nests
      - Ok - done!
  - Combine this model into previous R-model, to estimate S_juv[t] (i.e juvenile summer survival)
      - Ok - done

### Remainingg      
- Add specific model based on "known-fate" approach  for survival of radiomarked birds
- Prepare for presentation - which aspects to focus on



###### 25/12-2020
- Add model for known fate data for survival analysis based on radiomarked birds. 
 - Probably based on the binomial model
 
 
##### Christmas break 2020
- Known-fate model
- Add simmulation model - to assess bias and precision
- Update and annotate model code
- Prepare data from GBIF
- Draft manuscript for MEE


#### Known fate model

- Establish basics
    - ok - done
- Integrate with model M3
    - ok - done
- Prepare data
    - ok'ish
- Run model - check
    - ok'ish
    
#### Check code
- inital values - first year sometimes strange


## Progress plan Chloè and Erlend; 

### Chloè
- Check out the NIMBLE distance sampling library
- In particular - the half normal distr.
- NIMBLE version of full model
- Chloé prepare draft simmulation starting on full model
  - Sequential removal of data
  - Sensitivity to biases in population structure data
  

### Erlend

- Add "missing" parts [egg ++] and produce "full" model
- Start writing introduction ++ 
- Compare if the JAGS and NIMBLE versions produce similar results
- Erlend review code










