#' Write updated indicator data to the Nature Index (NI) database
#'
#' The function uploads the newly assembled indicator data to the NI database.
#' Provided the user has writing access, this will overwrite the data that is
#' currently in the database and should ONLY be done when the database needs to
#' be updated, and after the updated indicator data has been quality-checked. 
#' 
#' When attempting to write to the NI database, the used will be prompted to 
#' confirm the action prior to its execution. 
#' 
#' Executing this function requires accessing the NI database through a token
#' generated by `getToken` from the `NIcalc` package, and users are prompted to 
#' enter their NI database log-in credentials for that purpose. NI database 
#' credentials consist of a registered email address and a password. 
#' 
#' @param species character string or vector of character strings containing
#' the latin name of the species for which to upload/compare data
#' @param data_path character string specifying the directory in which the 
#' updated indicator data is stored.
#' 
#' @return
#' @export
#'
#' @examples
uploadData_NIdb <- function(indicatorData){
  
  ## Provide user credentials for NI database and request token
  myUserName_NIdb <- rstudioapi::askForPassword("NI database username") # = NINA email address
  myPassword_NIdb <- rstudioapi::askForPassword("NI database password")
  
  NIcalc::getToken(username = myUserName_NIdb,  
                   password = myPassword_NIdb,
                   #url = "https://www8.nina.no/NaturindeksAPITest"
                   url = "https://www8.nina.no/NaturindeksNiCalc"
  )
  
  # Ask the user for confirmation to write to database
  command <- askYesNo("Do you want to write to the database?", default = FALSE)
  
  # Write to database if confirmed (halt execution otherwise)
  if(!is.na(command) & command){
    
    message("Uploading new indicator data to NI database:")
    
    for(i in 1:length(indicatorData)){
      message(names(indicatorData)[i])
      NIcalc::writeIndicatorValues(indicatorData[[i]])
    }
  }else{
    message("Function halted.")
  }
}